name = "CRNHexagon"
uuid = "4d9daa3a-052f-4e6c-a389-3aa07aaa8b0a"
authors = ["Matthias Himmelmann <65544132+matthiashimmelmann@users.noreply.github.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
